### PR TITLE
SFT data preparation defaults

### PR DESCRIPTION
**Pull request by shtoshni**
Updating the SFT data prep defaults based on our discussions.

### CODE REVIEW

**Review by wedu-nvidia — APPROVED** [review]
looks good to me.

**Comment by Kipok** [comment]
Does this need to be updated https://github.com/Kipok/NeMo-Skills/blob/main/docs/openmathinstruct2/training.md#convert-to-sft-format?

**Comment by shtoshni** [comment]
> Does this need to be updated https://github.com/Kipok/NeMo-Skills/blob/main/docs/openmathinstruct2/training.md#convert-to-sft-format?

Oops, good catch. Didn't realize there's a data preparation command there as well.

**Review by Kipok — APPROVED** [review]

**Comment by Kipok** [comment]
@shtoshni please update tests with model argument and should be good to merge after that

**Comment by shtoshni** [comment]
Had to turn off length-based filtering for questions because the tests were failing. 
Those tests were passing on my local machine. Something to with the transformer library/HF_TOKEN setting.

**Pull request merged**
